apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-spc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quegrowth.labels" . | nindent 4 }}
    {{- toYaml .Values.rabbitmq.labels | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-secret
    type: Opaque
    data:
    - objectName: RABBITMQ-DEFAULT-PASS
      key: RABBITMQ_DEFAULT_PASS
    - objectName: RABBITMQ-DEFAULT-USER
      key: RABBITMQ_DEFAULT_USER
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.clientID }} # Setting this to use workload identity
    tenantId: {{ .Values.tenantId }}  # The tenant ID of the key vault
    keyvaultName: {{ .Values.rabbitmq.keyvaultName }}
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: RABBITMQ-DEFAULT-PASS
          objectType: secret
        - |
          objectName: RABBITMQ-DEFAULT-USER
          objectType: secret
