env: prod # Change to test/prod as needed
namespace: cuegrowth-prod # Change to test/prod as needed
imageRegistry: cuegrowthProdAcr.azurecr.io
serviceAccountName: workload-identity-sa
imageTag: latest # default tag; will be overridden in GitHub Actions
clientID: azurekeyvaultsecretsprovider-client-id # will be overridden in GitHub Actions
tenantId: tenant-ID-of-the-key-vault # will be overridden in GitHub Actions

rabbitmq:
  image: rabbitmq
  labels:
    app: cuegrowth-rabbitmq
  ports:
    amqp: 5672
    management: 15672
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 150
    targetMemoryUtilizationPercentage: 150
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "800Mi"
  keyvaultName: cuegrowth-rabmq-prod-kv
