apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None # Headless service
  selector:
    {{- toYaml .Values.valkey.labels | nindent 4 }}
    environment: {{ .Values.env }}
  ports:
    - name: valkey
      port: {{ .Values.valkey.port }}
      targetPort: {{ .Values.valkey.port }}
