apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-sfs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quegrowth.labels" . | nindent 4 }}
    {{- toYaml .Values.valkey.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.valkey.labels | nindent 6 }}
      environment: {{ .Values.env }}
  serviceName: "{{ .Release.Name }}-svc"
  replicas: {{ .Values.valkey.replicaCount }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.valkey.labels | nindent 8 }}
        environment: {{ .Values.env }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: valkey
          image: {{ .Values.imageRegistry }}/{{ .Values.valkey.image }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.valkey.port }}
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: quegrowth-valkey-{{ .Values.env }}
              mountPath: /data
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            {{- toYaml .Values.valkey.resources | nindent 12 }}
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Release.Name }}-spc
  volumeClaimTemplates:
    - metadata:
        name: quegrowth-valkey-{{ .Values.env }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi
        resources:
          requests:
            storage: 1Gi
