apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-worker-spc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quegrowth.labels" . | nindent 4 }}
    {{- toYaml .Values.worker.labels | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-worker-secret
    type: Opaque
    data:
    - objectName: APP-ENV
      key: APP_ENV
    - objectName: OTEL-DEPLOYMENT-ENVIRONMENT
      key: OTEL_DEPLOYMENT_ENVIRONMENT
    - objectName: OTEL-EXPORTER-OTLP-ENDPOINT
      key: OTEL_EXPORTER_OTLP_ENDPOINT
    - objectName: RABBITMQ-BROKER-URL
      key: RABBITMQ_BROKER_URL
    - objectName: RABBITMQ-QUEUE-NAME
      key: RABBITMQ_QUEUE_NAME
    - objectName: VALKEY-URL
      key: VALKEY_URL
    - objectName: VALKEY-PROCESSED-COUNT-KEY
      key: VALKEY_PROCESSED_COUNT_KEY
    - objectName: WORKER-NAME
      key: WORKER_NAME

  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.clientID }} # Setting this to use workload identity
    tenantId: {{ .Values.tenantId }}  # The tenant ID of the key vault
    keyvaultName: {{ .Values.worker.keyvaultName }}
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: APP-ENV
          objectType: secret
        - |
          objectName: OTEL-DEPLOYMENT-ENVIRONMENT
          objectType: secret
        - |
          objectName: OTEL-EXPORTER-OTLP-ENDPOINT
          objectType: secret
        - |
          objectName: RABBITMQ-BROKER-URL
          objectType: secret
        - |
          objectName: RABBITMQ-QUEUE-NAME
          objectType: secret
        - |
          objectName: VALKEY-URL
          objectType: secret
        - |
          objectName: VALKEY-PROCESSED-COUNT-KEY
          objectType: secret
        - |
          objectName: WORKER-NAME
          objectType: secret
