apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-deploy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quegrowth.labels" . | nindent 4 }}
    {{- toYaml .Values.worker.labels | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.worker.labels | nindent 6 }}
      environment: {{ .Values.env }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.worker.labels | nindent 8 }}
        environment: {{ .Values.env }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: worker
          image: {{ .Values.imageRegistry }}/{{ .Values.worker.image }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          command: ["/app/entrypoint_worker.sh"]
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-worker-secret
          volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Release.Name }}-worker-spc
