apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- toYaml .Values.api.labels | nindent 4 }}
    environment: {{ .Values.env }}
  ports:
    - name: api
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
